version: "2"
services:
  node:
    build: .
    volumes:
      - ./src:/workspace/src
      - ./client.js:/workspace/client.js
    ports:
      - 3000:3000
    command: "npm start"
    depends_on:
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379

  cache:
    image: redis/redis-stack-server:6.2.6-v10