version: "2"
services:
  node:
    build: .
    volumes:
      - ./src:/workspace/src
    ports:
      - 3000:3000
    command: "npm start"
    depends_on:
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379

  cache:
    image: redis:7.2.3-alpine